rm sequencing_runs.db
rm alembic/versions/*_autogenerated.py
# rm alembic/versions/*_view.py
alembic revision --autogenerate -m 'autogenerated'
sed -i s/"branch_labels = None"/"branch_labels = ['auto']"/ alembic/versions/*_autogenerated.py
# cp alembic/versions_backup/*_view.py alembic/versions
alembic upgrade auto@head
# alembic upgrade views@head
